

# This file was *autogenerated* from the file GoppaCode.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
class GoppaCode:

	def __init__(self, n, m, g):
		t = g.degree();
		F2 = GF(_sage_const_2 );
		F_2m = g.base_ring(); Z = F_2m.gen();
		PR_F_2m = g.parent(); X = PR_F_2m.gen();

		factor_list = list(factor(_sage_const_2 **m-_sage_const_1 )); final_factor_list = [];
		for i in range(len(factor_list)):
			for j in range(factor_list[i][_sage_const_1 ]):
				final_factor_list.append(factor_list[i][_sage_const_0 ]);

		while _sage_const_1 :
			primitive_root = F_2m.random_element();
			if primitive_root == _sage_const_0 :
				continue;
	
			for i in range(len(final_factor_list)):
				for j in itertools.combinations(final_factor_list,i):
					exponent = _sage_const_1 ;			
					for _ in range(len(j)):
						exponent *= j[_];			
					if primitive_root**(exponent) == _sage_const_1 :
						output = False;
						break;
					else:
						output = True;
						continue;
				if output == False:
					break;
			if output == True:
				#print 'primitive root: ',primitive_root;
				break;
		#primitive_root = F_2m([0, 0, 1, 0, 1]);#TODO
		print "primitive_root", BinRepr(primitive_root);
		#Initialize the code locators
		codelocators = [];
		for i in range(_sage_const_2 **m-_sage_const_1 ):
			codelocators.append(primitive_root**(i+_sage_const_1 ));
		codelocators.append(F_2m(_sage_const_0 ));
		print 'codelocators ', codelocators;
		#This is the same h to which Bernstein
		#refers in his polynomial view of a Goppa code
		h = PR_F_2m(_sage_const_1 );
		#for a_i in codelocators:
			#h = h*(X-a_i);
		
		#Gamma is a list of the polynomials
		#used to determine membership in the code
		gamma = [];
		for a_i in codelocators:
			gamma.append((h*((X-a_i).inverse_mod(g))).mod(g));

		#Calculate the parity-check matrix (as polynomials)
		#In other words, the first column of this matrix
		#has entries that correspond to the coefficients of
		#the first polynomial of gamma.
		H_check_poly = matrix(F_2m, t, n);
		for i in range(n):
			#print '__init__: gamma[%d]=' %(i);
			#print gamma[i];
			#print '__init__: coeffs=';
			coeffs = list(gamma[i]);

			for j in range(t):
			# Check to make sure the coefficient exists
			#(It may not if the polynomial is not of
			#degree t)
				if j < len(coeffs):
					H_check_poly[j,i] = coeffs[j];
				else:
					H_check_poly[j,i] = F_2m(_sage_const_0 );
		
		#Construct the binary parity-check matrix for the Goppa code.
		#Do so by converting each element of F_2^m to its binary
		#representation.
		H_Goppa = matrix(F2,m*H_check_poly.nrows(),H_check_poly.ncols());
		
		for i in range(H_check_poly.nrows()):
			for j in range(H_check_poly.ncols()):
				#print 'cnt=',i*n+j;
				#print '__init__: poly=',H_check_poly[i,j];
				be = bin(H_check_poly[i,j].integer_representation())[_sage_const_2 :];
				be = be[::-_sage_const_1 ];
				#print '__init__: be=',H_check_poly[i,j].integer_representation();
				#be = '0'*(m-len(be))+be; 
				be = be+'0'*(m-len(be));
				be = list(be);
				H_Goppa[m*i:m*(i+_sage_const_1 ),j] = vector(map(int,be));
				#print "H_Goppa ",H_Goppa[m*i:m*(i+1),j].transpose();
		
                #Construct the generator matrix for our code by computing
		#a basis for the null-space of H_Goppa. The null-space is,
		#by definition, the codewords of our code.
		#G_Goppa = H_Goppa.right_kernel().basis_matrix();
		G_Goppa = H_Goppa.transpose().kernel().basis_matrix();
		G_Goppa_poly = H_check_poly.transpose().kernel().basis_matrix();                

		print 'k=n-mt= ',n-m*g.degree();
		print 'H_goppa_poly rank ', H_check_poly.rank();
		print H_check_poly.str();
		print 'H_goppa rank ', H_Goppa.rank();
		print H_Goppa.str();
		
		print 'G_goppa_poly nrows', G_Goppa_poly.nrows();	
		print G_Goppa_poly.str();
		print 'G_goppa nrows', G_Goppa.nrows();	
		print G_Goppa.str();
		#Construct the syndrome calculator. This will be used
		#to simplify the calculation of syndromes for decoding.
		SyndromeCalculator = matrix(PR_F_2m, _sage_const_1 , len(codelocators));
		for i in range(len(codelocators)):
			SyndromeCalculator[_sage_const_0 ,i] = (X - codelocators[i]).inverse_mod(g);

		#Remember these values
		self._n = n;
		self._m = m;
		self._g = g;
		self._t = t;
		self._codelocators = codelocators;
		self._SyndromeCalculator = SyndromeCalculator;
		self._H_Goppa = H_Goppa;
		self._H_gRS = H_check_poly;
		self._G_Goppa = G_Goppa;

		self._R = _sage_const_0 ;self._alpha = _sage_const_0 ;self._beta = _sage_const_0 ;self._sigma = _sage_const_0 ;
		
	def Encode(self, message):
		#Encoding a k-bit binary message done by
		#multiplication on the right by the generator matrix.
		return (message*self._G_Goppa);

	def _split(self,p):
		# split polynomial p over F into even part po
		# and odd part p1 such that p(z) = p2 (z) + z p2 (z)
		Phi = p.parent()
		p0 = Phi([sqrt(c) for c in p.list()[_sage_const_0 ::_sage_const_2 ]]);
		p1 = Phi([sqrt(c) for c in p.list()[_sage_const_1 ::_sage_const_2 ]]);
		return (p0,p1);

	def _g_inverse(self, p):
		# returns the g-inverse of polynomial p
		(d,u,v) = xgcd(p,self.goppa_polynomial());
		return u.mod(self.goppa_polynomial());

	def _norm(self,a,b):
	#This is the way in which Bernstein indicates
	#the norm of a member of the lattice is
	#to be defined.
		X = self.goppa_polynomial().parent().gen();
		return _sage_const_2 **((a**_sage_const_2 +X*b**_sage_const_2 ).degree());

	def _lattice_basis_reduce(self, s):
		# a <- s   b <- v 
		g = self.goppa_polynomial();
		t = g.degree();
		a = []; a.append(_sage_const_0 );
		b = []; b.append(_sage_const_0 );
		(q,r) = g.quo_rem(s);
		(a[_sage_const_0 ],b[_sage_const_0 ]) = simplify((g - q*s, _sage_const_0  - q))
			
			
		#print 'lattice: a[0]=',BinRepr(a[0]);
		#print 'lattice: b[0]=',BinRepr(b[0]);
		

		#If the norm is already small enough, we
		#are done. Otherwise, intialize the base
		#case of the recursive process.
		#print 'norm: ',self._norm(a[0],b[0]);
		if self._norm(a[_sage_const_0 ],b[_sage_const_0 ]) > _sage_const_2 **t:
			a.append(_sage_const_0 ); b.append(_sage_const_0 );
			(q,r) = s.quo_rem(a[_sage_const_0 ]);
			(a[_sage_const_1 ],b[_sage_const_1 ]) = (r, _sage_const_1  - q*b[_sage_const_0 ]);
			if a[_sage_const_1 ] == _sage_const_0 :
				return (s,_sage_const_1 );	
			#print 'lattice: a[1]=',BinRepr(a[1]);
			#print 'lattice: b[1]=',BinRepr(b[1]);
			
		else:
			return (a[_sage_const_0 ], b[_sage_const_0 ]);
		#Continue subtracting integer multiples of
		#the shorter vector from the longer until
		#the produced vector has a small enough norm.
			
		i = _sage_const_1 ;
		while self._norm(a[i],b[i]) > _sage_const_2 **t:
			a.append(_sage_const_0 ); b.append(_sage_const_0 );
			(q,r) = a[i-_sage_const_1 ].quo_rem(a[i]);
			(a[i+_sage_const_1 ],b[i+_sage_const_1 ]) = (r, b[i-_sage_const_1 ] - q*b[i]);
			i+=_sage_const_1 ;
			#print 'lattice: a[',i,']= ',BinRepr(a[i]);
			#print 'lattice: b[',i,']= ',BinRepr(b[i]);
		return (a[i],b[i]);


	
	def _extended_euclidean(self, a,b,degree):
		# v*b = s mod a, a>b
		s = []; u = []; v = [];
		s.append(a); s.append(b);
		u.append(_sage_const_1 ); u.append(_sage_const_0 );
		v.append(_sage_const_0 ); v.append(_sage_const_1 );
		i=_sage_const_1 ;
		
		while s[i].degree() >= degree:
			i += _sage_const_1 ;	
			s.append(_sage_const_0 );u.append(_sage_const_0 );v.append(_sage_const_0 );
			(q,r) = s[i-_sage_const_2 ].quo_rem(s[i-_sage_const_1 ]);		
			s[i] = s[i-_sage_const_2 ] + q*s[i-_sage_const_1 ];
			u[i] = u[i-_sage_const_2 ] + q*u[i-_sage_const_1 ];
			v[i] = v[i-_sage_const_2 ] + q*v[i-_sage_const_1 ];
			#print 'euclidean: omega[i]=',BinRepr(s[i]);
			#print 'euclidean: sigma[i]=',BinRepr(v[i]);
		sigma = v[i]
		omega = s[i]
		return (sigma, omega);	 
	
	def _extended_euclidean_I(self,a,b,degree):
		s = []; u = []; v = [];
		s.append(a); s.append(b);
		u.append(_sage_const_1 ); u.append(_sage_const_0 );
		v.append(_sage_const_0 ); v.append(_sage_const_1 );
		i=_sage_const_1 ;	

		while s[i].degree() >= degree:
			i += _sage_const_1 ;
			q = _sage_const_0 ;
			t = s[i-_sage_const_2 ].degree()-s[i-_sage_const_1 ].degree();
			s.append(_sage_const_0 );u.append(_sage_const_0 );v.append(_sage_const_0 );
			while t >= _sage_const_0 :
				coeff1 = list(s[i-_sage_const_2 ])[-_sage_const_1 ];
				coeff2 = list(s[i-_sage_const_1 ])[-_sage_const_1 ];
				X = a.parent().gen();
				Q = coeff1 * _sage_const_1 /coeff2 * X**t;
				s[i] = s[i-_sage_const_2 ] + Q*s[i-_sage_const_1 ];
				q += Q;  
				s[i-_sage_const_2 ] = s[i];
				t = s[i-_sage_const_2 ].degree()-s[i-_sage_const_1 ].degree(); 
			u[i] = u[i-_sage_const_2 ] + q*u[i-_sage_const_1 ];
			v[i] = v[i-_sage_const_2 ] + q*v[i-_sage_const_1 ];

		sigma = v[i]
		omega = s[i]
		return (sigma, omega);
	
	def _extended_euclidean_II(self,a,b,degree):
		s = []; u = []; v = [];
		s.append(a); s.append(b);
		u.append(_sage_const_1 ); u.append(_sage_const_0 );
		v.append(_sage_const_0 ); v.append(_sage_const_1 );
		i=_sage_const_1 ;	
		
		while s[i].degree() >= degree:
			i += _sage_const_1 ;
			delta = _sage_const_1 ; q = _sage_const_0 ;
			t = s[i-_sage_const_2 ].degree()-s[i-_sage_const_1 ].degree();
			s.append(_sage_const_0 );u.append(_sage_const_0 );v.append(_sage_const_0 );
			tmp = s[i-_sage_const_2 ];
			while t >= _sage_const_0 :
				coeff1 = list(s[i-_sage_const_2 ])[-_sage_const_1 ];
				coeff2 = list(s[i-_sage_const_1 ])[-_sage_const_1 ];
				X = a.parent().gen();
				Q = coeff1 * X**t;
				s[i] = coeff2*s[i-_sage_const_2 ] - Q*s[i-_sage_const_1 ];
				delta *= coeff2;				
				q = coeff2*q + Q;  
				s[i-_sage_const_2 ] = s[i];
				t = s[i-_sage_const_2 ].degree()-s[i-_sage_const_1 ].degree(); 
			assert s[i] == delta*tmp - q*s[i-_sage_const_1 ], 'relation wrong!';
			u[i] = delta*u[i-_sage_const_2 ] - q*u[i-_sage_const_1 ];
			v[i] = delta*v[i-_sage_const_2 ] - q*v[i-_sage_const_1 ];

		sigma = v[i];
		omega = s[i];
		return (sigma, omega);	

		
	def Decode(self, word_, mode='Patterson'):
		g = self._g;
		word = copy(word_);
		X = g.parent().gen();

		#Compute the syndrome necessary for Patterson’s Algorithm.
		synd = self._SyndromeCalculator*word.transpose();		
		#print 'Decode: synd=', synd;
	
		syndrome_poly = _sage_const_0 ;
		for i in range (synd.nrows()):
			syndrome_poly += synd[i,_sage_const_0 ]*X**i
		
		if mode == 'Patterson':
			#We will decode codewords using Patterson’s Algorithm, error-locator polynomial returned.
			error = self.SyndromeDecode(syndrome_poly, 'Patterson');
			return word+error;
		
		elif mode == 'Euclidean':
			error = self.SyndromeDecode(syndrome_poly, 'Euclidean');	
			return word+error;
			
	
	def SyndromeDecode(self, syndrome_poly, mode='Patterson'):
		#Unlike Decode(), SyndromeDecode uses the syndrome polynomial as its input, outputs the error pattern.
			
		g = self.goppa_polynomial();
		X = g.parent().gen();
		error = matrix(GF(_sage_const_2 ),_sage_const_1 ,self.parity_check_matrix().ncols());
		
		if mode == 'Patterson':	
			#Compute the syndrome necessary for Patterson’s Algorithm.
			#Take the necessary square root
			(g0,g1) = self._split(g); sqrt_X = g0*self._g_inverse(g1);
		        T = syndrome_poly.inverse_mod(g);
		        		
			(T0,T1) = self._split(T - X);
			R = (T0+ sqrt_X*T1).mod(g);
		
			#Perform lattice basis reduction.
			(alpha, beta) = self._lattice_basis_reduce(R);

			#Construct the error-locator polynomial.
			sigma = (alpha*alpha) + (beta*beta)*X;
			print 'SyndromeDecode: sigma=', BinRepr(sigma);
			#Pre-test sigma
			if (X**(_sage_const_2 **m)).mod(sigma) != X:	
				print "sigma: Decodability Test Failed";
				return error;# return a zero vector 
			#For every root of the error polynomial,
			#correct the error induced at the corresponding index.
			for i in range(len(self._codelocators)):
				if sigma(self._codelocators[i]) == _sage_const_0 :
					error[_sage_const_0 ,i] = _sage_const_1 ;
			return error;

		elif mode == 'Euclidean':
			(sigma, omega) = self._extended_euclidean_II(g,syndrome_poly,floor(g.degree()/_sage_const_2 ));
			# print "Decode, sigma=",sigma;
			sigma = sigma/sigma.coefficients()[-_sage_const_1 ];
			#For every root of the error polynomial,
			#correct the error induced at the corresponding index.
			for i in range(len(self._codelocators)):
				if sigma(self._codelocators[i]) == _sage_const_0 :
					error[_sage_const_0 ,i] = _sage_const_1 ;
			return error;
			
	#Accessors
	def generator_matrix(self):
		return (self._G_Goppa);

	def goppa_polynomial(self):
		return (self._g);

	def parity_check_matrix(self):
		return (self._H_Goppa);
	
	def parity_check_poly_matrix(self):
		return (self._H_gRS);
	
	def R(self):
		return self._R;
	def error_locator(self):
		return (self._sigma, self._alpha, self._beta);

	



